services:
  db_mysql:
    container_name: db_mysql
    image: mysql
    ports:
      - "3311:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mirastom
    volumes:
      - /var/lib/mysqld:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8091:80"
    environment:
      - PMA_HOST=db_mysql
    depends_on:
      - db_mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
